name: "Pipeline Principal - TechMarket App v1.7.0"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1. Invocación de la plantilla de pruebas
  fase_pruebas_techmarket:
    uses: ./.github/workflows/template_test.yml
    with:
      node-version: '20.x' 

  # 2. Invocación de la plantilla de construcción
  fase_construccion_techmarket:
    needs: fase_pruebas_techmarket 
    uses: ./.github/workflows/template_build.yml
    with:
      image-name: 'techmarket-core-service' 
      tag: ${{ github.sha }} 
    secrets: inherit

  # 3. Invocación de la plantilla de despliegue
  fase_despliegue_techmarket:
    needs: fase_construccion_techmarket
    uses: ./.github/workflows/template_deploy.yml
    with:
      namespace: 'staging' 
      deployment-name: 'techmarket-deployment'
      image-name: 'techmarket-core-service'
      tag: ${{ github.sha }} 
    secrets: inherit
