name: "Pipeline Principal - TechMarket App v1.5.0"

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  # 1. Invocación de la plantilla de pruebas
  fase_pruebas_techmarket:
    uses: ./.github/workflows/template_test.yml
    with:
      node-version: '20.x' 

  # 2. Invocación de la plantilla de construcción
  fase_construccion_techmarket:
    needs: fase_pruebas_techmarket 
    uses: ./.github/workflows/template_build.yml
    with:
      image-name: 'techmarket-core-service' 
      tag: ${{ github.sha }} 
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}

  # 3. Invocación de la plantilla de despliegue
  fase_despliegue_techmarket:
    needs: fase_construccion_techmarket
    uses: ./.github/workflows/template_deploy.yml
    with:
      namespace: 'staging' 
      deployment-name: 'techmarket-deployment'
      image-name: 'techmarket-core-service'
      tag: ${{ github.sha }} 
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      aws-region: ${{ secrets.AWS_REGION }
      eks_cluster_name: ${{ secrets.EKS_CLUSTER_NAME }}
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
