name: "Template - Test v1.0.0"
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        description: "Versión de Node.js a utilizar"

jobs:
  test:
    name: Ejecutar Pruebas Unitarias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # Acción externa para obtener el código

      - name: Configurar Node.js
        uses: actions/setup-node@v4 # Acción externa para entorno de ejecución
        with:
          node-version: ${{ inputs.node-version }}

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test
