name: "Template - Build & Push v1.0.0"
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: "Nombre del repositorio Docker en ECR"
      tag:
        required: true
        type: string
        description: "Etiqueta (tag) de la imagen"
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true

jobs:
  build:
    name: Build y Push a ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          aws_session_token: ${{ secrets.aws_session_token }}
          aws_region: ${{ secrets.aws_region }}

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag y push de la imagen Docker
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: ${{ inputs.image-name }}
          IMAGE_TAG: ${{ inputs.tag }}
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
