name: "Template - Deploy to EKS v1.3.0"
on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      deployment-name:
        required: true
        type: string
      image-name:
        required: true
        type: string
      tag:
        required: true
        type: string
      AWS_ACCESS_KEY_ID:
        required: true
        type: string
      AWS_SECRET_ACCESS_KEY:
        required: true
        type: string
      AWS_SESSION_TOKEN:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      EKS_CLUSTER_NAME:
        required: true
        type: string

jobs:
  deploy:
    name: Despliegue en Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ inputs.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Obtener ID de la cuenta de AWS dinámicamente
        id: aws-account
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "account_id=$ACCOUNT_ID" >> $GITHUB_OUTPUT

      - name: Actualizar Kubeconfig
        run: aws eks update-kubeconfig --name ${{ inputs.EKS_CLUSTER_NAME }} --region ${{ inputs.AWS_REGION }}

      - name: Desplegar nueva imagen en EKS
        env:
          REGISTRY: ${{ steps.aws-account.outputs.account_id }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com
          IMAGE_NAME: ${{ inputs.image-name }}
          TAG: ${{ inputs.tag }}
        run: |
          kubectl set image deployment/${{ inputs.deployment-name }} \
          *=$REGISTRY/$IMAGE_NAME:$TAG -n ${{ inputs.namespace }}
